//
//  Preferences.m
//  <%= @project_name %>
//
//  Generated by <%= @author %> on <%= Date.today.strftime("%m/%d/%Y") %>
//  Copyright <%= Date.today.strftime("%Y") %> <%= @author %>. All rights reserved.
//

#import "Preferences.h"

@implementation Preferences

+(BOOL)preferencesSet {
  return !(
    <%= object.fields.map{|field|object.is_set?(field)}.join(" || \n    ") %>
  );
}

<% object.bulk_setters.each do |setter| -%>
+(void)<%= object.bulk_setter_name_for(setter) %> {
<% setter.each do |field| -%>
  [[NSUserDefaults standardUserDefaults] <%= object.setter_for_key(field[:type])%>:username forKey:@"<%= field[:name]%>"];
<% end -%>
}
<% end -%>

<% object.fields.each do |field| -%>
+(<%= field[:type] %>)<%= field[:name] %> {
  return [[NSUserDefaults standardUserDefaults] <%= object.type_for_key(field[:symbol_type])%>:@"<%= field[:name] %>"];
}
<% end -%>

@end
