//
//  Preferences.h
//  <%= @project_name %>
//
//  Generated by <%= @author %> on <%= Date.today.strftime("%m/%d/%Y") %>
//  Copyright <%= Date.today.strftime("%Y") %> <%= @author %>. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Preferences : NSObject {

}
+(BOOL)preferencesSet;

<% object.bulk_setters.each do |setter| %>
+(void)<%= object.bulk_setter_name_for(setter) %>;
<% end -%>

<% object.fields.each do |field| -%>
+(<%= field[:type] %>)<%= field[:name] %>;
<% end -%>

@end
