//
//  Preferences.h
//  MyApp
//
//  Generated by Ian Terrell on 03/22/2009
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Preferences : NSObject {

}
+(BOOL)preferencesSet;


+(void)setUsername:(NSString *)username andPassword:(NSString *)password;

+(NSString *)username;
+(NSString *)password;

+(NSString *)helloWorld;

@end
