//
//  Preferences.m
//  MyApp
//
//  Generated by Ian Terrell on 03/20/2009
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import "Preferences.h"

@implementation Preferences

+(BOOL)preferenceSet {
  return !(
    (([Preferences username] == nil) || ([[Preferences username] isEqualToString:@])) || 
    (([Preferences password] == nil) || ([[Preferences password] isEqualToString:@]))
  );
}

+(void)setUsername:(NSString *)username andPassword:(NSString *)password {
  [[NSUserDefaults standardUserDefaults] setObject:username forKey:@"username"];
  [[NSUserDefaults standardUserDefaults] setObject:username forKey:@"password"];
}

+(NSString *)username {
  return [[NSUserDefaults standardUserDefaults] stringForKey:@"username"];
}
+(NSString *)password {
  return [[NSUserDefaults standardUserDefaults] stringForKey:@"password"];
}

@end
