//
//  Preferences.m
//  MyApp
//
//  Generated by Ian Terrell on 03/22/2009
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import "Preferences.h"

@implementation Preferences

+(BOOL)preferencesSet {
  return !(
    (([Preferences username] == nil) || ([[Preferences username] isEqualToString:@""])) || 
    (([Preferences password] == nil) || ([[Preferences password] isEqualToString:@""]))
  );
}

+(void)setUsername:(NSString *)username andPassword:(NSString *)password {
  [[NSUserDefaults standardUserDefaults] setObject:username forKey:@"username"];
  [[NSUserDefaults standardUserDefaults] setObject:password forKey:@"password"];
}

+(NSString *)username {
  return [[NSUserDefaults standardUserDefaults] stringForKey:@"username"];
}
+(NSString *)password {
  return [[NSUserDefaults standardUserDefaults] stringForKey:@"password"];
}

+(NSString *)helloWorld {
      return @"Hello World!";

}

@end
