//
//  User.m
//  MyApp
//
//  Generated by Ian Terrell on 03/15/2009.
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import "User.h"

@implementation User

@synthesize username, userId, group, anotherGroup;

DECLARE_PROPERTIES(
  DECLARE_PROPERTY(@"username", @"@\"NSString\""),
  DECLARE_PROPERTY(@"userId", @"@\"NSInteger\""),
  DECLARE_PROPERTY(@"group", @"@\"Group\""),
  DECLARE_PROPERTY(@"anotherGroup", @"@\"Group\"")
)

- (void)dealloc
{
  [username release];
  [group release];
  [anotherGroup release];
	[super dealloc];
}

@end
