//
//  User.h
//  MyApp
//
//  Generated by Ian Terrell on 04/12/2009.
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "SQLitePersistentObject.h"

typedef enum {
  Fired,
  SuperFired
} UserState;

@class Group;

@interface User : SQLitePersistentObject {
  NSString *username;
  NSInteger userId;
  UserState state;
  Group *group;
  Group *anotherGroup;
}

@property (nonatomic,readwrite,retain) NSString *username;
@property (nonatomic,readwrite) NSInteger userId;
@property (nonatomic,readwrite) UserState state;
@property (nonatomic,readwrite,retain) Group *group;
@property (nonatomic,readwrite,retain) Group *anotherGroup;


+(void)deleteAll;

@end
