//
//  User.m
//  MyApp
//
//  Generated by Ian Terrell on 04/12/2009.
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import "User.h"
#import "SQLiteInstanceManager.h"

@implementation User

@synthesize username, userId, state, group, anotherGroup;

DECLARE_PROPERTIES(
  DECLARE_PROPERTY(@"username", @"@\"NSString\""),
  DECLARE_PROPERTY(@"userId", @"@\"NSInteger\""),
  DECLARE_PROPERTY(@"state", @"@\"UserState\""),
  DECLARE_PROPERTY(@"group", @"@\"Group\""),
  DECLARE_PROPERTY(@"anotherGroup", @"@\"Group\"")
)


+(void)deleteAll {
	NSString *sql = [NSString stringWithFormat:@"DELETE FROM %@;", [User tableName]];
  NSLog([NSString stringWithFormat:@"Executing SQL:  DELETE FROM %@;", [User tableName]]);
  SQLiteInstanceManager *manager = [SQLiteInstanceManager sharedManager];
  [manager executeUpdateSQL:sql];
  [manager vacuum];
  [User clearCache];
}

- (void)dealloc
{
  [username release];
  [group release];
  [anotherGroup release];
	[super dealloc];
}

@end
