//
//  User.h
//  MyApp
//
//  Generated by Ian Terrell on 03/15/2009.
//  Copyright 2009 Ian Terrell. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "SQLitePersistentObject.h"

@class Group;

@interface User : SQLitePersistentObject {
  NSString *username;
  NSInteger userId;
  Group *group;
  Group *anotherGroup;
}

@property (nonatomic,readwrite,retain) NSString *username;
@property (nonatomic,readwrite) NSInteger userId;
@property (nonatomic,readwrite,retain) Group *group;
@property (nonatomic,readwrite,retain) Group *anotherGroup;

@end
